### ISSUE TITLE
Exception when file not exists

### ISSUE THREAD

**Issue by sbaldovi** [fmeunier/wav2pzx#1]
Are you planning to add error handling?

$ java -jar wav2pzx-1.0.jar non-existing-file.wav output.pzx

```
java.io.FileNotFoundException: non-existing-file.wav (No such file or directory)
Apr 17, 2016 7:42:40 PM xyz.meunier.wav2pzx.WAV2PZX main
SEVERE: java.io.FileNotFoundException: non-existing-file.wav (No such file or directory)
java.io.FileNotFoundException: non-existing-file.wav (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at com.sun.media.sound.WaveFloatFileReader.getAudioInputStream(WaveFloatFileReader.java:164)
    at javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:1181)
    at xyz.meunier.wav2pzx.AudioFileTape.buildPulseList(AudioFileTape.java:63)
    at xyz.meunier.wav2pzx.WAV2PZX.main(WAV2PZX.java:83)
```

$ touch dummy.wav
$ java -jar wav2pzx-1.0.jar dummy.wav output.pzx

```
java.io.EOFException
Apr 17, 2016 7:53:18 PM xyz.meunier.wav2pzx.WAV2PZX main
SEVERE: java.io.EOFException
java.io.EOFException
    at java.io.DataInputStream.readInt(DataInputStream.java:392)
    at com.sun.media.sound.WaveFileReader.getFMT(WaveFileReader.java:234)
    at com.sun.media.sound.WaveFileReader.getAudioInputStream(WaveFileReader.java:199)
    at javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:1181)
    at xyz.meunier.wav2pzx.AudioFileTape.buildPulseList(AudioFileTape.java:63)
    at xyz.meunier.wav2pzx.WAV2PZX.main(WAV2PZX.java:83)
```

**Comment by fmeunier** [comment]
Thanks, yes I intended to have some better terminal error output than that (the second doesn't give me much to work with!) :)

```
$ java -jar wav2pzx-1.0.1-SNAPSHOT.jar non-existing-file.wav output.pzx
Error opening file non-existing-file.wav: non-existing-file.wav (No such file or directory)
wav2pzx: usage: wav2pzx <infile.wav> <outfile.pzx>

$ java -jar wav2pzx-1.0.1-SNAPSHOT.jar dummy.wav output.pzx
Error with file dummy.wav: java.io.EOFException
```

7c14b1e
